### ISSUE TITLE
Lab Report 1 Feedback

### ISSUE THREAD

**Issue by Amaar-V** [MelodyyyYin/cse15l-lab-reports#1]
Here is your feedback for Lab Report 1:

- [ ] All relevant URLs written as markdown links
  - References VSCode website but does not provide markdown link
- [x] All relevant code examples written with backticks (```)
- [x] All screenshots correspond to the described steps
- [x] All titles of sections are formatted as headers or similar
- [x] Lab report is on its own page, not the index page
- [ ] Last example counts keystrokes and shows how to run remotely saving time
  - Does not count keystrokes (see lab 1 part 7) and does not provide text to supplement the image of what is happening (how are you running remotely?) (what tricks do you use to accomplish this?)
- [x] Text is formatted in a way that was easy for grader to read

Additional comments from your grader:
**Well Done!**
*Please comment on this issue if you have any questions or need clarification, thanks*

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by MelodyyyYin** [comment]
"References VSCode website but does not provide markdown link" 
-does that mean I need to submit the link that end with.md?
"Does not count keystrokes (see lab 1 part 7) and does not provide text to supplement the image of what is happening (how are you running remotely?) (what tricks do you use to accomplish this?)"
-what is keystrokes? is it like I use up arrow key to put some command in the terminal?

**Comment by Amaar-V** [comment]
Hi,

- The markdown link is the text that we can click and it will take us to a website, [like this](https://www.markdownguide.org/basic-syntax/#links). Add a link to VSCode so a reader of your report can download it.
- A keystroke is anytime you press a key or click your mouse, you just need to provide an image of executing a java file remotely using a command and count the number of keys pressed in trying to do that command.

**Comment by MelodyyyYin** [comment]
I submitted a regrade request on gradescope 3 days ago but have not received a response yet. SInce ddl is 5pm , how long can I get the response?

**Comment by Amaar-V** [comment]
Hey, I will look at regrades this weekend! If you have any questions or want me to look at something before I look at the regrade request then please comment here.

**Comment by Amaar-V** [comment]
Well Done!
